# ============= local ollama settings =================
API_KEY="ollama"
API_URL="http://localhost:11434/v1"
MODEL="llama3.1:latest"
# ==============================================

HUGGINGFACE_API_KEY="hf_"
ASSEMBLYAI_API_KEY="aai_"